# Generated by Django 5.0.3 on 2024-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.PositiveIntegerField(verbose_name='номер версии'),
        ),
    ]
